headers:
  - iostream
  - cstdlib
  - vector
  - string

classes:
  Entity:
    attributes:
        public:
          - int x
          - float y
          - std::string name
        private:
          - int z
    getter_setters: on

  Student:
    attributes:
        private:
          - int id
          - std::string name
          - double moy
