system_headers:
  - iostream
  - cstdlib
  - vector
  - string

project_headers:
  - animal.h

classes:
  Entity:
    attributes:
        public:
          - int x
          - float y
          - std::string name
        private:
            - int z
    getters_setters: on

  Student:
    attributes:
        private:
          - int id
          - std::string name
          - double moy
    getters_setters: on
